# Import data file

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# from sklearn import tree

df = pd.read_excel('D:/KKU/AjOff/AjOffData.xlsx',sheet_name='CutoffNorVsCCA')
y=df.iloc[:,[3]]
X=df.iloc[:,[4,5,6,7,8]]
## Split train and test
#X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=42) #best
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=30) #best


# Setup the parameters and distributions to sample from: param_dist
param_dist = {"max_depth": [9,6,3], 
              "max_features": [1,2,3,4, 5],
              "min_samples_leaf": [1,2,3,4,5,6,7,8,9,10],
              "criterion": ["gini", "entropy"]}

# Initiate the decision tree
dt = DecisionTreeClassifier(random_state=43)

# Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(dt, param_dist, cv=5) #GridSearchCV

# Fit it to the data
tree_cv.fit(X_train,y_train)


# Print the tuned parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))
print(tree_cv.scoring)
# tree_cv.best_estimator_ => Get the best parameter
# tree_cv.cv_results_ => Get the all result of grid search 

## Create Tree from optimal parameters
#dt_optNorCCA = DecisionTreeClassifier(criterion='gini',max_depth=9,max_features=5,min_samples_leaf=2,random_state=43)
#dt_optNorCCA.fit(X_train,y_train)
#y_pred=dt_optNorCCA.predict(X_test)

# Create the fine-tuned tree
dt_OptNorCCA = tree_cv.best_estimator_
dt_OptNorCCA.fit(X_train,y_train)
y_pred=dt_OptNorCCA.predict(X_test)
#print(tree_cv.best_estimator_)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
r = export_text(dt_optNorCCA)
print(r)
import pickle
s = pickle.dumps(dt_optNorCCA)
#clf2 = pickle.loads(s)

Tuned Decision Tree Parameters: {'criterion': 'gini', 'max_depth': 9, 'max_features': 4, 'min_samples_leaf': 4}
Best score is 0.9106060606060605
None
[[10  0]
 [ 3 11]]
              precision    recall  f1-score   support

           0       0.77      1.00      0.87        10
           1       1.00      0.79      0.88        14

    accuracy                           0.88        24
   macro avg       0.88      0.89      0.87        24
weighted avg       0.90      0.88      0.88        24



NameError: name 'dt_optNorCCA' is not defined

In [6]:
import pandas as pd
import numpy as np
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# from sklearn import tree

df = pd.read_excel('D:/KKU/AjOff/AjOffData.xlsx',sheet_name='Cutoff NonCCAVsCCA')
y=df.iloc[:,[3]]
X=df.iloc[:,[4,5,6,7,8]]
## Split train and test
#X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=20)
#X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=53)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=28)

# Setup the parameters and distributions to sample from: param_dist
param_dist = {"max_depth": [9,6,3], 
              "max_features": [1,2,3,4, 5],
              "min_samples_leaf": [1,2,3,4,5,6,7,8,9,10],
              "criterion": ["gini", "entropy"]}

# Initiate the decision tree
dt = DecisionTreeClassifier(random_state=43)

# Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(dt, param_dist, cv=5) #GridSearchCV

# Fit it to the data
tree_cv.fit(X_train,y_train)


# Print the tuned parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))
print(tree_cv.scoring)
# tree_cv.best_estimator_ => Get the best parameter
# tree_cv.cv_results_ => Get the all result of grid search 

## Create Tree from optimal parameters
#dt_optNorCCA = DecisionTreeClassifier(criterion='gini',max_depth=9,max_features=5,min_samples_leaf=2,random_state=43)
#dt_optNorCCA.fit(X_train,y_train)
#y_pred=dt_optNorCCA.predict(X_test)

#tree_cv.best_estimator_.fit(X_train,y_train)
dt_optNorCCA = tree_cv.best_estimator_
dt_optNorCCA.fit(X_train,y_train)
y_pred=dt_optNorCCA.predict(X_test)
#print(tree_cv.best_estimator_)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
r = export_text(dt_optNorCCA)
print(r)
import pickle
s = pickle.dumps(dt_optNorCCA)
#clf2 = pickle.loads(s)

Tuned Decision Tree Parameters: {'criterion': 'gini', 'max_depth': 9, 'max_features': 3, 'min_samples_leaf': 7}
Best score is 0.75
None
[[11  3]
 [ 2  8]]
              precision    recall  f1-score   support

           0       0.85      0.79      0.81        14
           1       0.73      0.80      0.76        10

    accuracy                           0.79        24
   macro avg       0.79      0.79      0.79        24
weighted avg       0.80      0.79      0.79        24

|--- feature_4 <= 0.50
|   |--- feature_2 <= 0.50
|   |   |--- class: 0
|   |--- feature_2 >  0.50
|   |   |--- class: 0
|--- feature_4 >  0.50
|   |--- feature_2 <= 0.50
|   |   |--- class: 1
|   |--- feature_2 >  0.50
|   |   |--- class: 1



In [2]:
import pandas as pd
import numpy as np
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# from sklearn import tree

df = pd.read_excel('D:/KKU/AjOff/AjOffData.xlsx',sheet_name='Cutoff NorVsNonCCA')
y=df.iloc[:,[3]]
X=df.iloc[:,[4,5,6,7,8]]
## Split train and test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

# Setup the parameters and distributions to sample from: param_dist
param_dist = {"max_depth": [9,6,3], 
              "max_features": [1,2,3,4, 5],
              "min_samples_leaf": [1,2,3,4,5,6,7,8,9,10],
              "criterion": ["gini", "entropy"]}

# Initiate the decision tree
dt = DecisionTreeClassifier(random_state=43)

# Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(dt, param_dist, cv=5) #GridSearchCV

# Fit it to the data
tree_cv.fit(X_train,y_train)


# Print the tuned parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))
print(tree_cv.scoring)
# tree_cv.best_estimator_ => Get the best parameter
# tree_cv.cv_results_ => Get the all result of grid search 

## Create Tree from optimal parameters
#dt_optNorCCA = DecisionTreeClassifier(criterion='gini',max_depth=9,max_features=5,min_samples_leaf=2,random_state=43)
#dt_optNorCCA.fit(X_train,y_train)
#y_pred=dt_optNorCCA.predict(X_test)

#tree_cv.best_estimator_.fit(X_train,y_train)
dt_optNorCCA = tree_cv.best_estimator_
dt_optNorCCA.fit(X_train,y_train)
y_pred=dt_optNorCCA.predict(X_test)
#print(tree_cv.best_estimator_)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
r = export_text(dt_optNorCCA)
print(r)
import pickle
s = pickle.dumps(dt_optNorCCA)
#clf2 = pickle.loads(s)

Tuned Decision Tree Parameters: {'criterion': 'gini', 'max_depth': 9, 'max_features': 1, 'min_samples_leaf': 4}
Best score is 0.8227272727272729
None
[[10  3]
 [ 2  9]]
              precision    recall  f1-score   support

           0       0.83      0.77      0.80        13
           1       0.75      0.82      0.78        11

    accuracy                           0.79        24
   macro avg       0.79      0.79      0.79        24
weighted avg       0.80      0.79      0.79        24

|--- feature_0 <= 0.50
|   |--- feature_3 <= 0.50
|   |   |--- class: 0
|   |--- feature_3 >  0.50
|   |   |--- feature_1 <= 0.50
|   |   |   |--- feature_2 <= 0.50
|   |   |   |   |--- class: 0
|   |   |   |--- feature_2 >  0.50
|   |   |   |   |--- class: 0
|   |   |--- feature_1 >  0.50
|   |   |   |--- feature_2 <= 0.50
|   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |--- class: 1
|   |   |   |--- feature_2 >  0.

In [ ]:
tree_cv.best_estimator_

In [8]:
tree_cv.cv_results_

{'mean_fit_time': array([0.00159521, 0.00159583, 0.00179524, 0.00139618, 0.00159574,
        0.00139627, 0.00159564, 0.00139627, 0.00139613, 0.00139637,
        0.00139885, 0.00159564, 0.00139623, 0.00139623, 0.00159588,
        0.00159578, 0.00159569, 0.00159564, 0.00159578, 0.00159574,
        0.00199451, 0.00159578, 0.00159578, 0.00159574, 0.00139613,
        0.00139637, 0.00139637, 0.00139627, 0.00139618, 0.00159564,
        0.00140858, 0.0012898 , 0.00159574, 0.00159578, 0.00179515,
        0.00179524, 0.00139618, 0.00159564, 0.00159578, 0.00159574,
        0.00139623, 0.00159836, 0.00159578, 0.00139632, 0.00139627,
        0.00179524, 0.00159569, 0.00179515, 0.00159569, 0.00159574,
        0.00139632, 0.00159583, 0.00159569, 0.00159597, 0.00179529,
        0.00159574, 0.00139627, 0.00159578, 0.00159578, 0.00159583,
        0.00159583, 0.00159574, 0.00139637, 0.0017952 , 0.00179524,
        0.00159583, 0.0017952 , 0.00159574, 0.00159588, 0.00139627,
        0.00159574, 0.00159569,

In [10]:
dir(tree_cv)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_iter',
 'n_jobs',
 'n_splits_',
 'param_distributions',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'random_state',
 'refit',
 'refit_t

In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
# from sklearn import tree

df = pd.read_excel('D:/KKU/AjOff/AjOffData.xlsx',sheet_name='CutoffNorVsCCA')
y=df.iloc[:,[3]]
X=df.iloc[:,[4,5,6,7,8]]
# Split train and test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

# Initiate the decision tree
dt = DecisionTreeClassifier(max_depth=6)
# Fit dt to the training set
dt.fit(X_train,y_train)

# Predict test set labels
y_pred = dt.predict(X_test)
# Compute test set accuracy  
acc = accuracy_score(y_test,y_pred)
print("Test set accuracy: {:.2f}".format(acc))
# Generate the confusion matrix and classification report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Test set accuracy: 0.96
[[13  0]
 [ 1 10]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.91      0.95        11

    accuracy                           0.96        24
   macro avg       0.96      0.95      0.96        24
weighted avg       0.96      0.96      0.96        24



In [18]:
y=df.iloc[:,[3]]
X=df.iloc[:,[4,5,6,7,8]]

In [19]:
type(X)

pandas.core.frame.DataFrame

In [20]:
np.shape(X)

(80, 5)

In [17]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [18]:
range(1,10)

range(1, 10)

In [19]:
print(range(1,10))

range(1, 10)
